kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 2
  template:
    metadata:
      name: demo-job
      labels:
        app: batch-job
    spec:
      containers:
      - name: batch-job-cont
        image: busybox:latest
        command: ["sh", "-c", "echo My first job && sleep 10"]  
      restartPolicy: Never

